[build]
  command = "CI= npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  REACT_APP_AUTH0_DOMAIN = "dev-wz5dzkvkd1ckck0z.us.auth0.com"
  REACT_APP_AUTH0_CLIENT_ID = "Dshomcv8KhsX9hbjWjtpZVFQMS4eNzJQ"
  REACT_APP_AUTH0_REDIRECT_URI = "https://vocal-medovik-4ff155.netlify.app/login"

[[redirects]]
  from = "/api/*"
  to = "https://madison88-itsm-platform.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
